### ISSUE TITLE
Removing all elements from a Dictionary

### ISSUE THREAD

**Issue by Libbum** [andyferris/Dictionaries.jl#30]
Hi!

I'm not sure if I overlooked this, but I can't find a method in the README that would allow me to remove all items in a `Dictionary`. 

This way gives me behaviour that seems a bit arbitrary:

```julia
julia> dict = Dictionary(["a", "b", "c"], [1, 2, 3])
3-element Dictionary{String,Int64}
 "a" │ 1
 "b" │ 2
 "c" │ 3

julia> for k in keys(dict)
           unset!(dict, k) # Or delete!
       end

julia> dict
1-element Dictionary{String,Int64}
 "b" │ 2
```

**Comment by andyferris** [comment]
@Libbum does the `empty!` function work? The documentation is a bit sparse on functions that already exist in `Base`. Methods like `empty!` that work on both arrays like `Vector` and dictionaries like `Dict` probably already work (but aren’t explicitly documented here). 

You shouldn’t insert or delete elements of a collection while iterating it, because the iterator state can become inconsistent with the container. You’ll find similar problems with arrays and `Dict` (and containers in the majority of other programming languages, too).

**Comment by Libbum** [comment]
Thanks Andy. Can confirm `empty!` does indeed work.

Your second point makes sense too, so perhaps before closing this issue, I could ask how you would go deleting all values matching a criteria?

Using the same example above:
```julia
dict = Dictionary(["a", "b", "c"], [1, 2, 3])
to_delete = findall(v -> v>1)
# should I iterate over to_delete here, or is there a safer way?
```

**Comment by andyferris** [comment]
You could try `filter!` - the predicate is flipped around so it's like `filter!(v -> v <= 1, dict)`.

**Comment by andyferris** [comment]
> `# should I iterate over to_delete here, or is there a safer way?`

To answer this question - you can iterate `to_delete` safely while mutating `dict`. (Try to consider the container being iterated as immutable).

**Comment by Libbum** [comment]
Awesome. `filter!` works, and that rule of thumb helps a lot. Thanks mate!
