### ISSUE TITLE
get() with a default of different type

### ISSUE THREAD

**Issue by aplavin** [andyferris/Dictionaries.jl#44]
For some reason, `get(dict, k, default)` tries to convert `default` to the dict value type. Clearly, this fails in the following typical case:
```
dict = Dictionary(Dict(:a => 1, :b => 2))
get(dict, :a, -1)       # == 1, ok
get(dict, :x, -1)       # ==-1, ok
get(dict, :x, nothing)  # MethodError: Cannot `convert` an object of type Nothing to an object of type Int64
```

**Comment by andyferris** [comment]
This is interesting. I suppose that the standard `Base.Dict` does allow this. 

On the other hand, this couldn’t possible make sense for `set!` so it lacks a certain sense of aesthetic symmetry. 

On the other hand though, the number of times I’ve used `get(dict, key, nothing)` is actually quite high. Although I would frequently check for `nothing` pretty soon - so with Dictionaries.jl I’d sometimes use `gettoken` and `gettokenvalue`. 

We should probably make this change to help with usability and consistency with `Base`. (Although we do some things differently here compared to `Base`, we’re not trying to be contrary). 

@aplavin do you feel brave enough to make a PR? Otherwise I’ll get around to it, at some stage...

**Comment by aplavin** [comment]
`Base.Dict` does indeed allow this `get` behavior.
Currently, I just convert `Dictionaries` to `Base.Dicts` after receiving them from functions in `SplitApplyCombine`, so this is not really a big issue for me. Also, I'm not familiar with all this "token" thing which is used everywhere internally.
Just wanted to let you know of such an inconsistency.

**Comment by andyferris** [comment]
Okay - thank you for the report. I've made a new release with more flexible `get`, see https://github.com/JuliaRegistries/General/pull/31339.

> Currently, I just convert Dictionaries to Base.Dicts after receiving them from functions in SplitApplyCombine

This is an interesting data point to me. If you don't mind me asking, what is the reason for that?

(Also, ideally with functions like `group` it would be nice if you could choose the output container)

**Comment by aplavin** [comment]
Thanks a lot for the very prompt modification! Seems to work for me.

Sorry, I wasn't precise enough: it's not that I _always_ convert to `Dict`! Only in cases when my further code depends on this `get` behavior, or there is a function somewhere that takes `::Dict` arguments. Otherwise, `Dictionary` works completely fine for me. Great that unlike the base version it is ordered, this is my main gripe with `Base.Dict` :)

Btw, I really like the `SplitApplyCombine` package and recently started using it for basically all data manipulation, together with `Base` functions like `map`.

**Comment by andyferris** [comment]
Thank you for the kind feedback, @aplavin :). Feel free to let me know if there are any other rough edges to smooth out.
