### ISSUE TITLE
unsetting key can lead to undefined reference

### ISSUE THREAD

**Issue by piever** [andyferris/Dictionaries.jl#84]
I've run into the following bug when calling `unset!` on a `Dictionary`. Somehow the values of the dictionary get corrupted, but it only happens with some data types.

```julia
julia> d = Dictionary{Symbol, Any}([:a, :b, :c, :d], [1, [1], [1], nothing])
4-element Dictionary{Symbol, Any}
 :a │ 1
 :b │ [1]
 :c │ [1]
 :d │ nothing

julia> unset!(d, :a)
3-element Dictionary{Symbol, Any}
 :b │ [1]
 :c │ [1]
 :d │ nothing

julia> d.values
4-element Vector{Any}:
 #undef
    [1]
    [1]
    nothing
```

On Dictionaries 0.3.16 this caused `collect(pairs(d))` to fail (with access to undefined reference), but now  (v0.3.17) that seems to work. Opening this in case it is worrisome that `d.values` and `values(d)` do not have the same content.

**Comment by andyferris** [comment]
Please note that `d.values` is not equivalent to `values(d)` because upon deletion the arrays have holes in them, which are skipped on iteration. So `length(values(d)) == 3` but `length(d.values) == 4` in this case. In 0.3.16 there were definitely bugs, but the described behavior here is now as intended and seems correct to me.

Does that make sense?
